[v1]
"api 0.1.0 (path+file:///Users/dmitriysemin/Workspace/modeller/api)" = ["api"]
"cargo-audit 0.17.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-audit"]
"cargo-deny 0.13.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-deny"]
"cargo-edit 0.10.4 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-add",
    "cargo-rm",
    "cargo-set-version",
    "cargo-upgrade",
]
"cargo-expand 1.0.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-expand"]
"cargo-info 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-info"]
"cargo-make 0.36.6 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-make",
    "makers",
]
"cargo-modules 0.5.7 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-modules"]
"cargo-nextest 0.9.47 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-nextest"]
"cargo-tarpaulin 0.20.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-tarpaulin"]
"cargo-udeps 0.1.35 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-udeps"]
"cargo-watch 7.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["cargo-watch"]
"diesel_cli 1.4.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["diesel"]
"fyrox-template 0.6.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["fyrox-template"]
"https 1.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "http",
    "httplz",
]
"rust_ledger 0.4.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["rust_ledger"]
"sqlx-cli 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = [
    "cargo-sqlx",
    "sqlx",
]
"stylua 0.14.3 (registry+https://github.com/rust-lang/crates.io-index)" = ["stylua"]
"trunk 0.16.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["trunk"]
"wasm-gc 0.1.6 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-gc"]
"wasm-pack 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = ["wasm-pack"]
