---
style:
  tag:
    color: "dark_green"
    width_percentage: 26
    min_width: 20
  comment:
    color: blue
    width_percentage: 42
    min_width: 45
  snippet:
    color: white

finder:
  command: fzf

cheats:
  paths:
    - ~/.navi/

shell:
  command: zsh
